# # Application aware intentions can only be applied to services that use the HTTP protocol
# # so you must first define service default config entries for the targetted
# # services.
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: go-movies-app
spec:
  protocol: "http"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: go-movies-favorites-app
spec:
  protocol: "http"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: go-movies-favorites
spec:
  # Name of the destination service affected by this ServiceIntentions entry
  destination:
    name: go-movies-favorites
  # The set of traffic sources affected by this ServiceIntentions entry
  sources:
  # The first affected traffic source-maps to service name of inbound traffic source
  - name: go-movies-app
    # The set of permissions to apply when frontend is the traffic source
    # The first permission to match in the list is terminal and stops further evaluation.
    permissions:
    # Add this to always deny traffic from the frontend service to /health route
    - action: allow
      http:
        pathExact: "/health"
    # This permission now defines the conditions that should be allowed
    # Allo traffic to all paths for the GET, PUT, POST, DELETE verbs as long as an
    # api-token header is present
    - action: allow
      http:
        pathPrefix: "/"
        methods:
        - GET
        - PUT
        - POST
        - DELETE
        header:
        - name: "Authorization"
          present: true
    # Define a deny intention for all other traffic
    - action: deny
      http:
        pathPrefix: "/"
