apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  config:
    envoy_tracing_json: '{"http":{"name":"envoy.zipkin","config":{"collector_cluster":"jaeger_9411","collector_endpoint":"/api/v2/spans"}}}'
    members: 3
  meshGateway:
    mode: local