---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-go-demo
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-go-demo-v1
  labels:
    app: vault-go-demo
    version: v1
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: vault-go-demo
      version: v1
  template:
    metadata: 
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-protocol: "http"
        consul.hashicorp.com/service-tags: "v1"
        consul.hashicorp.com/connect-service-upstreams: "vault:8200, pq-postgresql:5432"
      name: vault-go-demo
      labels:
        app: vault-go-demo
        version: v1
    spec:
      serviceAccountName: vault-auth
      automountServiceAccountToken: true
      containers:
        - name: vault-go-demo
          image: aklaas2/vault-go-demo:latest
          ports:
          - containerPort: 9090
            protocol: TCP
