apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-movies-app-v2
  labels:
    app: go-movies-app
    version: v2
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: go-movies-app
      version: v2
  template:
    metadata: 
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-protocol: "http"
        "consul.hashicorp.com/service-tags": "v2"
        consul.hashicorp.com/connect-service-upstreams: "vault:8200, pq-postgresql:5432, go-movies-favorites-app:8081"
      name: go-movies-app
      labels:
        app: go-movies-app
        version: v2
    spec:
      #fix: go-movies-app
      serviceAccountName: vault-auth
      automountServiceAccountToken: true
      containers:
        - name: go-movies-app
          image: aklaas2/go-movies-app-v2:latest
          ports:
          - containerPort: 8080
            protocol: TCP
