apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-movies-favorites-app
  labels:
    app: go-movies-favorites-app
    version: v1
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: go-movies-favorites-app
      version: v1
  template:
    metadata: 
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-protocol: "http"
        "consul.hashicorp.com/service-tags": "v1"
      name: go-movies-favorites-app
      labels:
        app: go-movies-favorites-app
        version: v1
    spec:
      #fix: go-movies-app
      serviceAccountName: vault-auth
      automountServiceAccountToken: true
      containers:
        - name: go-movies-favorites-app
          image: aklaas2/go-movies-favorites-app:latest
          ports:
          - containerPort: 8081
            protocol: TCP
