kind: Service
apiVersion: v1
metadata:
  name: go-movies-app-v2
spec:
  selector:
    app: go-movies-app
    version: v2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer